### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gigantz** [gigantz/reactend-express#4]
Hey there,

- [x] Routes' children as a res params `<Get path="/"><Res.Content json={} text="" ... /></Get>`
- [x] Prepare environment to build package
- [ ] Caching
- [ ] Docs/Wiki
- [ ] React Hooks for backend
- [ ] Support `css.modules`
